version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: xmongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xbackend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - DATABASE_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=efaturas
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xfrontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
